FROM python:3.12-slim

WORKDIR /app

COPY backend/requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY backend/app /app/app
COPY scripts /app/scripts

CMD ["python", "--version"]
